In [14]:
# importing the necessary library
import pandas as pd

In [15]:
# Shaping of raw global conflicts dataset, it is too big to fit on github, so preprocessing has been done in advance
#keep_columns = ["year", "country", "best"]
#df_conflict = df_conflict[keep_columns].rename(columns={"country": "Area", "year": "Year", "best": "Casualties"}
#).loc[(df_conflict["year"] >= 2001) & (df_conflict["year"] <= 2020)
#].groupby(["Area", "Year"]).sum()
#df_conflict.to_csv(path + r"\conflict_data.csv")

In [16]:
#index to merge on with countries and years that we have y data for
df_base = pd.read_csv("../data/country_time_base.csv")

#output (y)
df_undernourishment = pd.read_csv(r"../data/undernourishment_data.csv")

#input (X)
#gloabl conflicts
df_conflict = pd.read_csv(r"../data/conflict_data.csv")
#climate
df_temp = pd.read_csv(r"../data/temp_data.csv")
df_rain = pd.read_csv(r"../data/rain_data.csv")
df_ndvi = pd.read_csv(r"../data/ndvi_data.csv")
#economics
df_GDP = pd.read_csv(r"../data/GDP_data.csv")
df_GNI = pd.read_csv(r"../data/GNI_data.csv")
df_prod = pd.read_csv(r"../data/production_data.csv")

In [17]:
df_undernourishment = df_undernourishment[["Area Code (M49)", "Year", "Value"
]].rename(columns={"Area Code (M49)": "M49", "Value": "Undernourishment (%)"})

df_GDP = df_GDP[["Area Code (M49)", "Year", "Value"
]].rename(columns={"Area Code (M49)": "M49", "Value": "GDP (MUSD)"})

df_GNI = df_GNI[["Area Code (M49)", "Year", "Value"
]].rename(columns={"Area Code (M49)": "M49", "Value": "GNI (MUSD)"})

df_prod = df_prod[["Area Code (M49)", "Year", "Value"
]].rename(columns={"Area Code (M49)": "M49", "Value": "Food Prod. Index"})

In [18]:
df_comb_temp = df_base.merge(df_GDP, on=["M49", "Year"], how="left"
).merge(df_GNI, on=["M49", "Year"], how="left"
).merge(df_prod, on=["M49", "Year"], how="left"
).merge(df_temp, on=["GAUL", "Year"], how="left"
).merge(df_rain, on=["GAUL", "Year"], how="left"
).merge(df_ndvi, on=["GAUL", "Year"], how="left"
).merge(df_conflict, on=["Area", "Year"], how="left"
).merge(df_undernourishment, on=["M49", "Year"], how="left"
).drop(columns=["Unnamed: 0_x", "Unnamed: 0_y"])

# Saving the dataset
df_comb_temp.to_csv(r"../data/combined_dataset_temp.csv")

# Having a first look
df_comb_temp.head()

/Users/sonic171717/opt/anaconda3/lib/python3.9/site-packages/pandas/core/frame.py:9190: FutureWarning: Passing 'suffixes' which cause duplicate columns {'Unnamed: 0_x'} in the result is deprecated and will raise a MergeError in a future version.
  return merge(

,GAUL,M49,Area,Year,GDP (MUSD),GNI (MUSD),Food Prod. Index,Temperature,Precipitation,NDVI,Casualties,Undernourishment (%)
0,1,4,Afghanistan,2001,3598.470576,3598.407195,62.42,286.086560,42.992387,1064.486468,5553.0,47.8
1,1,4,Afghanistan,2002,4141.523943,4134.295420,75.74,285.637743,64.661574,1040.450950,1157.0,45.6
2,1,4,Afghanistan,2003,4729.042179,4721.728965,77.83,284.996151,74.464959,972.493440,944.0,40.6
3,1,4,Afghanistan,2004,5388.482107,5396.722695,75.77,285.864614,66.059247,937.723550,817.0,38
4,1,4,Afghanistan,2005,6220.574147,6231.622214,84.68,284.481630,78.640260,980.545636,1711.0,36.1